// Shim to align @supabase/supabase-js generic defaults so that
// `ReturnType<typeof createClient>` matches the loose `SupabaseClient<any, ...>`
// returned by `createClient(url, key)` without explicit generics.
// Used by the email queue route generated by Lovable's email infra setup,
// where the project's Database type does not yet include email tables.
import '@supabase/supabase-js'

declare module '@supabase/supabase-js' {
  // Override the createClient function signature defaults to use `any`
  // instead of the strict `unknown / never` defaults from newer versions.
  export function createClient(
    supabaseUrl: string,
    supabaseKey: string,
    options?: any
  ): import('@supabase/supabase-js').SupabaseClient<any, any, any, any, any>
}
