import { useState } from "react";
import { ChevronDown, ChevronUp, Download } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useFinancialInputs } from "@/contexts/financial-inputs";

export type WaterfallFallback = {
  revenue: number;
  cogs: number;
  fixedCosts: number;
  interest: number;
  tax: number;
};

type Step = {
  label: string;
  value: number;
  barWidth: number;
  color: string;
  subtractLabel?: string;
  subtractValue?: number;
  showStatus: boolean;
};

function fmt(n: number) {
  return `R\u00a0${Math.round(n).toLocaleString("en-ZA")}`;
}

function pct(n: number, total: number) {
  if (!total) return "—";
  return `${((n / total) * 100).toFixed(1)}%`;
}

function getStatus(p: number): { label: string; color: string; bg: string } {
  if (p >= 0.2)
    return { label: "HEALTHY",  color: "#4caf82", bg: "rgba(76,175,130,0.15)" };
  if (p >= 0.1)
    return { label: "AT RISK",  color: "#d4a550", bg: "rgba(212,165,80,0.15)" };
  return       { label: "CRITICAL", color: "#e05c5c", bg: "rgba(224,92,92,0.15)" };
}

function exportPDF(steps: Step[], revenue: number) {
  const rows = steps
    .map((s) => {
      const p = revenue ? s.value / revenue : 0;
      const pctVal = pct(s.value, revenue);
      const deductRow =
        s.subtractLabel && (s.subtractValue ?? 0) > 0
          ? `<tr><td colspan="3" style="font-size:12px;color:#888;font-style:italic;padding:8px 0 2px 0">&ldquo; ${s.subtractLabel}: <span style="color:#c0392b;font-weight:700">(${fmt(s.subtractValue!)})</span></td></tr>`
          : "";
      const statusArr =
        p >= 0.2
          ? ["HEALTHY", "#1a7a4a"]
          : p >= 0.1
            ? ["AT RISK", "#b8860b"]
            : ["CRITICAL", "#c0392b"];
      const badge = s.showStatus
        ? `<span style="font-size:10px;font-weight:800;letter-spacing:0.08em;padding:3px 7px;border-radius:4px;background:${statusArr[1]}20;color:${statusArr[1]};border:1px solid ${statusArr[1]}">${statusArr[0]}</span>`
        : "";
      return `${deductRow}<tr>
        <td style="width:200px;font-size:13px;padding:8px 0;vertical-align:middle">
          <strong>${s.label}</strong><br/>
          <small style="font-size:11px;color:#888">${fmt(s.value)} &middot; ${pctVal} of revenue</small>
        </td>
        <td style="padding:0 20px;vertical-align:middle">
          <div style="height:24px;background:#f0f0f0;border-radius:4px;overflow:hidden">
            <div style="height:100%;width:${Math.max(s.barWidth, 0)}%;background:${s.color};border-radius:4px"></div>
          </div>
        </td>
        <td style="width:120px;text-align:right;font-weight:700;font-size:13px;white-space:nowrap;vertical-align:middle">${pctVal} ${badge}</td>
      </tr>`;
    })
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Profitability Waterfall &mdash; Mil&#333;n</title>
  <style>
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:'Segoe UI',Arial,sans-serif;background:#fff;color:#111;padding:40px}
    h1{font-size:26px;font-weight:900;color:#0a1628;margin-bottom:4px}
    .sub{font-size:13px;color:#888;margin-bottom:32px}
    table{width:100%;border-collapse:collapse}
    .footer{margin-top:40px;font-size:11px;color:#aaa;border-top:1px solid #eee;padding-top:12px}
    @media print{body{padding:20px}}
  </style>
</head>
<body>
  <h1>Profitability Waterfall</h1>
  <div class="sub">How R1 of revenue becomes profit &middot; Generated ${new Date().toLocaleDateString("en-ZA")} &middot; Mil&#333;n</div>
  <table>${rows}</table>
  <div class="footer">Generated by Mil&#333;n &middot; Confidential &middot; ${new Date().getFullYear()}</div>
  <script>window.onload=function(){window.print();window.onafterprint=function(){window.close();};}</script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (win) {
    win.document.write(html);
    win.document.close();
  }
}

export function ProfitabilityWaterfall({
  fallback,
}: {
  fallback?: WaterfallFallback;
}) {
  const { weeklyInputs } = useFinancialInputs();
  const [open, setOpen] = useState(true);

  const agg = Object.values(weeklyInputs.weeks).reduce(
    (acc, w) => ({
      revenue:     acc.revenue     + (w.revenue     || 0),
      costOfSales: acc.costOfSales + (w.costOfSales || 0),
      fixedCosts:  acc.fixedCosts  + (w.fixedCosts  || 0),
      interest:    acc.interest    + (w.interest    || 0),
      tax:         acc.tax         + (w.tax         || 0),
    }),
    { revenue: 0, costOfSales: 0, fixedCosts: 0, interest: 0, tax: 0 },
  );

  const hasWeekly = agg.revenue > 0 || agg.costOfSales > 0;

  const revenue      = hasWeekly ? agg.revenue     : (fallback?.revenue    ?? 0);
  const costOfSales  = hasWeekly ? agg.costOfSales : (fallback?.cogs       ?? 0);
  const fixedCosts   = hasWeekly ? agg.fixedCosts  : (fallback?.fixedCosts ?? 0);
  const interest     = hasWeekly ? agg.interest    : (fallback?.interest   ?? 0);
  const tax          = hasWeekly ? agg.tax         : (fallback?.tax        ?? 0);

  const grossProfit     = revenue - costOfSales;
  const operatingProfit = grossProfit - fixedCosts;
  const ebt             = operatingProfit - interest;
  const netProfit       = ebt - tax;

  const steps: Step[] = [
    {
      label:    "Revenue",
      value:    revenue,
      barWidth: 100,
      color:    "#1a3a5c",
      showStatus: false,
    },
    {
      label:         "Gross Profit",
      value:         grossProfit,
      barWidth:      revenue ? (grossProfit / revenue) * 100 : 0,
      color:         "#c9a96a",
      subtractLabel: "Cost of Sales",
      subtractValue: costOfSales,
      showStatus:    true,
    },
    {
      label:         "Operating Profit",
      value:         operatingProfit,
      barWidth:      revenue ? (operatingProfit / revenue) * 100 : 0,
      color:         "#4caf82",
      subtractLabel: "Operating Expenses",
      subtractValue: fixedCosts,
      showStatus:    true,
    },
    {
      label:         "Earnings Before Tax",
      value:         ebt,
      barWidth:      revenue ? (ebt / revenue) * 100 : 0,
      color:         "#6b7fa3",
      subtractLabel: "Interest & Finance",
      subtractValue: interest,
      showStatus:    false,
    },
    {
      label:         "Net Profit",
      value:         netProfit,
      barWidth:      revenue ? (netProfit / revenue) * 100 : 0,
      color:         "#d4a550",
      subtractLabel: "Income Tax",
      subtractValue: tax,
      showStatus:    true,
    },
  ];

  return (
    <Card className="border border-slate-800 bg-slate-900/60 shadow-sm print:hidden">
      <CardHeader className="border-b border-slate-800 pb-3">
        <div className="flex items-center justify-between gap-3">
          <div
            className="flex-1 cursor-pointer"
            onClick={() => setOpen((o) => !o)}
          >
            <CardTitle className="text-sm font-semibold text-slate-100">
              Profitability Waterfall
            </CardTitle>
            <p className="mt-0.5 text-[11px] text-slate-500">
              How R1 of revenue becomes profit
              {hasWeekly ? " · aggregated weekly data" : " · period inputs"}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <Button
              size="sm"
              variant="outline"
              className="h-7 gap-1.5 border-[#d4a550]/40 bg-[#d4a550]/10 px-2.5 text-[10px] text-[#d4a550] hover:bg-[#d4a550]/20"
              onClick={(e) => {
                e.stopPropagation();
                exportPDF(steps, revenue);
              }}
            >
              <Download className="h-3 w-3" />
              Export PDF
            </Button>
            <button
              className="p-1 text-[#d4a550]"
              onClick={() => setOpen((o) => !o)}
            >
              {open ? (
                <ChevronUp className="h-4 w-4" />
              ) : (
                <ChevronDown className="h-4 w-4" />
              )}
            </button>
          </div>
        </div>
      </CardHeader>

      {open && (
        <CardContent className="space-y-1 pb-4 pt-4">
          {revenue === 0 && (
            <p className="mb-3 text-xs italic text-slate-500">
              Enter revenue figures in Financial Inputs or Weekly Inputs above to populate the waterfall.
            </p>
          )}

          {steps.map((step, i) => {
            const p = revenue ? step.value / revenue : 0;
            const status = step.showStatus ? getStatus(p) : null;

            return (
              <div key={i}>
                {step.subtractLabel && (step.subtractValue ?? 0) > 0 && (
                  <div className="pb-1 pl-1 pt-2.5 text-[11px] italic text-slate-500">
                    &ldquo; {step.subtractLabel}:{" "}
                    <span className="font-semibold text-rose-400">
                      ({fmt(step.subtractValue!)})
                    </span>
                  </div>
                )}

                <div className="flex items-center gap-3 py-2">
                  <div className="w-36 shrink-0">
                    <div className="text-xs font-bold text-slate-100">
                      {step.label}
                    </div>
                    <div className="mt-0.5 text-sm font-extrabold text-white">
                      {fmt(step.value)}
                    </div>
                    <div className="mt-0.5 text-[10px] text-slate-500">
                      {pct(step.value, revenue)} of rev.
                    </div>
                  </div>

                  <div className="h-7 flex-1 overflow-hidden rounded-md bg-white/5">
                    <div
                      className="h-full min-w-[4px] rounded-md transition-[width] duration-500 ease-out"
                      style={{
                        width: `${Math.max(step.barWidth, 0)}%`,
                        background: step.color,
                      }}
                    />
                  </div>

                  <div className="flex w-24 shrink-0 flex-col items-end gap-1">
                    <span className="text-sm font-bold text-white">
                      {pct(step.value, revenue)}
                    </span>
                    {status && (
                      <span
                        className="rounded border px-1.5 py-0.5 text-[9px] font-extrabold uppercase tracking-wide"
                        style={{
                          color: status.color,
                          background: status.bg,
                          borderColor: status.color,
                        }}
                      >
                        {status.label}
                      </span>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </CardContent>
      )}
    </Card>
  );
}
