// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-vibes/Editorial.tsx": () => import("../components/mockups/dashboard-vibes/Editorial.tsx"),
  "./components/mockups/dashboard-vibes/Neon.tsx": () => import("../components/mockups/dashboard-vibes/Neon.tsx"),
  "./components/mockups/dashboard-vibes/Terminal.tsx": () => import("../components/mockups/dashboard-vibes/Terminal.tsx")
};
