/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForOwnersRouteImport } from './routes/for-owners'
import { Route as ForAccountantsRouteImport } from './routes/for-accountants'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as LhUnsubscribeRouteImport } from './routes/lh/unsubscribe'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiClientErrorRouteImport } from './routes/api/client-error'
import { Route as AckTokenRouteImport } from './routes/ack.$token'
import { Route as AuthenticatedOpsRouteImport } from './routes/_authenticated/ops'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiResendWebhookRouteImport } from './routes/api/resend/webhook'
import { Route as ApiQboCallbackRouteImport } from './routes/api/qbo/callback'
import { Route as AuthenticatedSettingsBrandRouteImport } from './routes/_authenticated/settings.brand'
import { Route as AuthenticatedReportsDemoRouteImport } from './routes/_authenticated/reports.demo'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForOwnersRoute = ForOwnersRouteImport.update({
  id: '/for-owners',
  path: '/for-owners',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAccountantsRoute = ForAccountantsRouteImport.update({
  id: '/for-accountants',
  path: '/for-accountants',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LhUnsubscribeRoute = LhUnsubscribeRouteImport.update({
  id: '/lh/unsubscribe',
  path: '/lh/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientErrorRoute = ApiClientErrorRouteImport.update({
  id: '/api/client-error',
  path: '/api/client-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AckTokenRoute = AckTokenRouteImport.update({
  id: '/ack/$token',
  path: '/ack/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOpsRoute = AuthenticatedOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResendWebhookRoute = ApiResendWebhookRouteImport.update({
  id: '/api/resend/webhook',
  path: '/api/resend/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQboCallbackRoute = ApiQboCallbackRouteImport.update({
  id: '/api/qbo/callback',
  path: '/api/qbo/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsBrandRoute =
  AuthenticatedSettingsBrandRouteImport.update({
    id: '/settings/brand',
    path: '/settings/brand',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsDemoRoute =
  AuthenticatedReportsDemoRouteImport.update({
    id: '/reports/demo',
    path: '/reports/demo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/faq': typeof FaqRoute
  '/for-accountants': typeof ForAccountantsRoute
  '/for-owners': typeof ForOwnersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ops': typeof AuthenticatedOpsRoute
  '/ack/$token': typeof AckTokenRoute
  '/api/client-error': typeof ApiClientErrorRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lh/unsubscribe': typeof LhUnsubscribeRoute
  '/t/$token': typeof TTokenRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/reports/demo': typeof AuthenticatedReportsDemoRoute
  '/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/api/qbo/callback': typeof ApiQboCallbackRoute
  '/api/resend/webhook': typeof ApiResendWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/faq': typeof FaqRoute
  '/for-accountants': typeof ForAccountantsRoute
  '/for-owners': typeof ForOwnersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ops': typeof AuthenticatedOpsRoute
  '/ack/$token': typeof AckTokenRoute
  '/api/client-error': typeof ApiClientErrorRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lh/unsubscribe': typeof LhUnsubscribeRoute
  '/t/$token': typeof TTokenRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/reports/demo': typeof AuthenticatedReportsDemoRoute
  '/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/api/qbo/callback': typeof ApiQboCallbackRoute
  '/api/resend/webhook': typeof ApiResendWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/faq': typeof FaqRoute
  '/for-accountants': typeof ForAccountantsRoute
  '/for-owners': typeof ForOwnersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ops': typeof AuthenticatedOpsRoute
  '/ack/$token': typeof AckTokenRoute
  '/api/client-error': typeof ApiClientErrorRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lh/unsubscribe': typeof LhUnsubscribeRoute
  '/t/$token': typeof TTokenRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/reports/demo': typeof AuthenticatedReportsDemoRoute
  '/_authenticated/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/api/qbo/callback': typeof ApiQboCallbackRoute
  '/api/resend/webhook': typeof ApiResendWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/auth/callback'
    | '/faq'
    | '/for-accountants'
    | '/for-owners'
    | '/reset-password'
    | '/unsubscribe'
    | '/dashboard'
    | '/ops'
    | '/ack/$token'
    | '/api/client-error'
    | '/email/unsubscribe'
    | '/lh/unsubscribe'
    | '/t/$token'
    | '/clients/$clientId'
    | '/reports/demo'
    | '/settings/brand'
    | '/api/qbo/callback'
    | '/api/resend/webhook'
    | '/lovable/email/suppression'
    | '/reports/'
    | '/settings/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/auth/callback'
    | '/faq'
    | '/for-accountants'
    | '/for-owners'
    | '/reset-password'
    | '/unsubscribe'
    | '/dashboard'
    | '/ops'
    | '/ack/$token'
    | '/api/client-error'
    | '/email/unsubscribe'
    | '/lh/unsubscribe'
    | '/t/$token'
    | '/clients/$clientId'
    | '/reports/demo'
    | '/settings/brand'
    | '/api/qbo/callback'
    | '/api/resend/webhook'
    | '/lovable/email/suppression'
    | '/reports'
    | '/settings'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/auth'
    | '/auth/callback'
    | '/faq'
    | '/for-accountants'
    | '/for-owners'
    | '/reset-password'
    | '/unsubscribe'
    | '/_authenticated/dashboard'
    | '/_authenticated/ops'
    | '/ack/$token'
    | '/api/client-error'
    | '/email/unsubscribe'
    | '/lh/unsubscribe'
    | '/t/$token'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/reports/demo'
    | '/_authenticated/settings/brand'
    | '/api/qbo/callback'
    | '/api/resend/webhook'
    | '/lovable/email/suppression'
    | '/_authenticated/reports/'
    | '/_authenticated/settings/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  FaqRoute: typeof FaqRoute
  ForAccountantsRoute: typeof ForAccountantsRoute
  ForOwnersRoute: typeof ForOwnersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AckTokenRoute: typeof AckTokenRoute
  ApiClientErrorRoute: typeof ApiClientErrorRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LhUnsubscribeRoute: typeof LhUnsubscribeRoute
  TTokenRoute: typeof TTokenRoute
  ApiQboCallbackRoute: typeof ApiQboCallbackRoute
  ApiResendWebhookRoute: typeof ApiResendWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-owners': {
      id: '/for-owners'
      path: '/for-owners'
      fullPath: '/for-owners'
      preLoaderRoute: typeof ForOwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-accountants': {
      id: '/for-accountants'
      path: '/for-accountants'
      fullPath: '/for-accountants'
      preLoaderRoute: typeof ForAccountantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lh/unsubscribe': {
      id: '/lh/unsubscribe'
      path: '/lh/unsubscribe'
      fullPath: '/lh/unsubscribe'
      preLoaderRoute: typeof LhUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/client-error': {
      id: '/api/client-error'
      path: '/api/client-error'
      fullPath: '/api/client-error'
      preLoaderRoute: typeof ApiClientErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ack/$token': {
      id: '/ack/$token'
      path: '/ack/$token'
      fullPath: '/ack/$token'
      preLoaderRoute: typeof AckTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ops': {
      id: '/_authenticated/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof AuthenticatedOpsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resend/webhook': {
      id: '/api/resend/webhook'
      path: '/api/resend/webhook'
      fullPath: '/api/resend/webhook'
      preLoaderRoute: typeof ApiResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qbo/callback': {
      id: '/api/qbo/callback'
      path: '/api/qbo/callback'
      fullPath: '/api/qbo/callback'
      preLoaderRoute: typeof ApiQboCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/brand': {
      id: '/_authenticated/settings/brand'
      path: '/settings/brand'
      fullPath: '/settings/brand'
      preLoaderRoute: typeof AuthenticatedSettingsBrandRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/demo': {
      id: '/_authenticated/reports/demo'
      path: '/reports/demo'
      fullPath: '/reports/demo'
      preLoaderRoute: typeof AuthenticatedReportsDemoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOpsRoute: typeof AuthenticatedOpsRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedReportsDemoRoute: typeof AuthenticatedReportsDemoRoute
  AuthenticatedSettingsBrandRoute: typeof AuthenticatedSettingsBrandRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOpsRoute: AuthenticatedOpsRoute,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedReportsDemoRoute: AuthenticatedReportsDemoRoute,
  AuthenticatedSettingsBrandRoute: AuthenticatedSettingsBrandRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  FaqRoute: FaqRoute,
  ForAccountantsRoute: ForAccountantsRoute,
  ForOwnersRoute: ForOwnersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AckTokenRoute: AckTokenRoute,
  ApiClientErrorRoute: ApiClientErrorRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LhUnsubscribeRoute: LhUnsubscribeRoute,
  TTokenRoute: TTokenRoute,
  ApiQboCallbackRoute: ApiQboCallbackRoute,
  ApiResendWebhookRoute: ApiResendWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
