// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  // `payload` is the raw server-function input forwarded by TanStack Start.
  // We inspect it here to enforce impersonation scope centrally so that every
  // server function using this middleware is protected without needing
  // per-function assertClientScope() calls.
  async ({ next, data: payload }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Response(message, { status: 500 });
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Response('Unauthorized: No request headers available', { status: 401 });
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Response('Unauthorized: No authorization header provided', { status: 401 });
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Response('Unauthorized: Only Bearer tokens are supported', { status: 401 });
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Response('Unauthorized: No token provided', { status: 401 });
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data: authData, error } = await supabase.auth.getClaims(token);
    if (error || !authData?.claims) {
      throw new Response('Unauthorized: Invalid token', { status: 401 });
    }

    if (!authData.claims.sub) {
      throw new Response('Unauthorized: No user ID found in token', { status: 401 });
    }

    const actingAsClientId = request.headers.get('x-acting-as-client-id');
    let validatedActingAsClientId: string | null = null;

    if (actingAsClientId) {
      const { data: auditRow } = await supabase
        .from('impersonation_audit')
        .select('id')
        .eq('firm_user_id', authData.claims.sub)
        .eq('client_id', actingAsClientId)
        .is('ended_at', null)
        .maybeSingle();

      if (!auditRow) {
        throw new Response('Forbidden: Invalid or expired impersonation scope', { status: 403 });
      }
      validatedActingAsClientId = actingAsClientId;
    }

    // Central impersonation-scope guard: when acting as a client, any server
    // function whose input contains a `clientId` field must target that exact
    // client — mismatch is rejected here before the handler runs.
    if (validatedActingAsClientId) {
      const inputClientId = (payload as Record<string, unknown>)?.clientId;
      if (typeof inputClientId === 'string' && inputClientId !== validatedActingAsClientId) {
        throw new Response(
          'Forbidden: request clientId is outside the current impersonation scope',
          { status: 403 },
        );
      }
    }

    return next({
      context: {
        supabase,
        userId: authData.claims.sub,
        claims: authData.claims,
        actingAsClientId: validatedActingAsClientId,
      },
    })
  }
)
