// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { actingAsHeaderForPath } from '../../lib/acting-as-client'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    const actingAsClientId = typeof sessionStorage !== 'undefined'
      ? sessionStorage.getItem('acting_as_client_id')
      : null
    const pathname = typeof location !== 'undefined' ? location.pathname : ''
    const headers: Record<string, string> = {}
    if (token) headers['Authorization'] = `Bearer ${token}`
    // Firm pages (/clients/:id, dashboard) use the firm principal. Sending the
    // owner-board client id makes every other client's server function 403.
    if (actingAsClientId && actingAsHeaderForPath(pathname)) {
      headers['x-acting-as-client-id'] = actingAsClientId
    }
    return next({ headers })
  },
)
